//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DienDanCongNgheThongTin.Models.framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FooterHelp
    {
        public string MaHelp { get; set; }
        public string TenHelp { get; set; }
        public string Link { get; set; }
    }
}
