//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DienDanCongNgheThongTin.Models.framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public string MaTinTuc { get; set; }
        public string TieuDe { get; set; }
        public string MaChuyenMuc { get; set; }
        public string MoTa { get; set; }
        public string TacGia { get; set; }
        public string imgUrl { get; set; }
    
        public virtual ChuyenMuc ChuyenMuc { get; set; }
    }
}
